// WAP to add two 8-bit numbers using interrupt of 8051.

MOV DPTR,#4000H		// INITIALIZE EXTERNAL MEMORY WITH DPTR
MOV A,#07H			//FIRST NUMBER IN ACCUMULATOR
MOV R3,#06H         //R0-R7 ANY REGISTER FOR SECOND NUMBER
ADD A,R3
MOVX @DPTR,A
END